List<String> items = [
  'Recommended',
  'Topwear',
  'Headwear',
  'Dress',
  'Jewellery',
  'Bags',
  'Sandal',
  'Gloves',
  'Beauty Accessories',
  'Accessories',
  'Apparel Set',
  'Bath and Body',
  'Belts',
  'Bottomwear',
  'Cufflinks',
  'Eyes',
  'Eyewear',
  'Flip Flops',
  'Fragrance',
  'Free Gifts',
  'Hair',
  'Home Furnishing',
  'Innerwear',
  'Lips',
  'Loungewear and Nightwear',
  'Makeup',
  'Mufflers',
  'Nails',
  'Perfumes',
  'Saree',
  'Scarves',
  'Shoe Accessories',
  'Shoes',
  'Skin',
  'Skin Care',
  'Socks',
  'Sports Accessories',
  'Sports Equipment',
  'Stoles',
  'Ties',
  'Umbrellas',
  'Vouchers',
  'Wallets',
  'Watches',
  'Water Bottle',
  'Wristbands',
];
