// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnVT3kNm85zZzhIBh5lWn6YKoiXDsLDEA',
    appId: '1:114665140833:web:ed2c1ad60fa1556c62f020',
    messagingSenderId: '114665140833',
    projectId: 'on-budget-35521',
    authDomain: 'on-budget-35521.firebaseapp.com',
    storageBucket: 'on-budget-35521.appspot.com',
    measurementId: 'G-GTZHKV831R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYi_-G-_FK-JGZQLjv1M9i624c8wI3tgM',
    appId: '1:114665140833:android:1e61f60a8158222c62f020',
    messagingSenderId: '114665140833',
    projectId: 'on-budget-35521',
    storageBucket: 'on-budget-35521.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMDtR95MZXF1bmuieHXzGTOM80Fpdabqk',
    appId: '1:114665140833:ios:cc01f9932bb3dc4f62f020',
    messagingSenderId: '114665140833',
    projectId: 'on-budget-35521',
    storageBucket: 'on-budget-35521.appspot.com',
    iosBundleId: 'com.example.onBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMDtR95MZXF1bmuieHXzGTOM80Fpdabqk',
    appId: '1:114665140833:ios:cc01f9932bb3dc4f62f020',
    messagingSenderId: '114665140833',
    projectId: 'on-budget-35521',
    storageBucket: 'on-budget-35521.appspot.com',
    iosBundleId: 'com.example.onBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnVT3kNm85zZzhIBh5lWn6YKoiXDsLDEA',
    appId: '1:114665140833:web:dffc62d2e2ff999f62f020',
    messagingSenderId: '114665140833',
    projectId: 'on-budget-35521',
    authDomain: 'on-budget-35521.firebaseapp.com',
    storageBucket: 'on-budget-35521.appspot.com',
    measurementId: 'G-JHE88XNW34',
  );
}
